name: geniac
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - certifi=2022.6.15=py310hff52083_0
  - git=2.35.3=pl5321h04cb727_0
  - git-lfs=3.2.0=ha770c72_0
  - make=4.3=hd18ef5c_1
  - nextflow=22.04.5=h4a94de4_0
  - pip=22.1.2=pyhd8ed1ab_0
  - python=3.10.5=ha86cf86_0_cpython
  - geniac::apptainer=1.0.3=h3fd9d12_1
  - pip:
    - colorlog==6.5.0
    - dotty-dict==1.3.0
    - cmake==3.21.3
    - geniac
    - GitPython==3.1.20
    - pre-commit==2.15.0
    - pytest==6.2.5
    - pytest-cov==3.0.0
    - pytest-datadir==1.3.1
    - pytest-datafiles==2.0
    - pytest-icdiff==0.5
    - pytest-sugar==0.9.4
    - setuptools-scm==6.3.2
    - tox-conda==0.8.3
    - validators==0.18.2
    - wheel==0.37.0
